forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class LoginForm(FlaskForm):

    email = EmailField("E-mail", validators=[DataRequired()], render_kw={
        'placeholder': "Email"
    })

    password = PasswordField("Palavra-passe", validators=[DataRequired()],render_kw={
        'placeholder': "Palavra-passe"
    })

    submit = SubmitField("Iniciar sessão")

routes/author_route.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from forms.author_form import AuthorForm
from forms.password_form import PasswordForm
from forms.login_form import LoginForm
from models.user_model import Author
from models.post_model import Post
from db.db import db
from oauth_config import OauthConfig
from flask_login import login_user, logout_user, current_user, login_required
from extensions import login_manager
from forms.post_form import PostForm
from flask_ckeditor.utils import cleanify
from werkzeug.utils import secure_filename
import uuid as uuid
import os
from utils import check_file


author_bp = Blueprint("user", __name__)

#REGISTO DE USUÁRIO COM GOOGLE
@author_bp.route("/OauthRegister")
def OauthRegister():
    return OauthConfig.google.authorize_redirect(url_for("user.google_callback", _external=True))

#LOGIN COM GOOGLE
@author_bp.route("/OauthLogin")
def OauthLogin():
    return OauthConfig.google.authorize_redirect(url_for("user.google_callback", _external=True))

#Capturar o id do user na sessão

@login_manager.user_loader
def load_user(user_id):
    return Author.query.get(int(user_id))

#GOOGLE CALLBACK
@author_bp.route("/google_callback")
def google_callback():
    token = OauthConfig.google.authorize_access_token()

    if not token:
        flash("Não foi possível a autenticação com o google", "danger")
        return redirect(url_for("index.index"))
    try:
        user_info = OauthConfig.google.parse_id_token(token, None)
        author = Author.query.filter_by(email = user_info['email']).first()

        if not author:
            author = Author(
                name = user_info['name'],
                email = user_info['email']
            )
            db.session.add(author)
            db.session.commit()
           
        login_user(author)
        return redirect(url_for("user.dashboard"))
    
    except Exception as e:
        flash("Houve um erro ao recuperar dados da google", "danger")

    return redirect(url_for("user.dashboard"))
    

#Rota para registo de autor
@author_bp.route("/register", methods=["GET",'POST'])
def register():
    form = AuthorForm()

    if form.errors:
        for error in form.errors:
            print(error)
    if form.validate_on_submit():
       
        author = Author.query.filter_by(email = form.email.data).first()
        if not author:
            session['author_name'] = form.name.data
            session['author_email'] = form.email.data
            return redirect(url_for("user.create_password"))
        flash("User already registered, go to login", "warning")
        
    return render_template("register.html", form = form)


#Rota para a criação da palavra-passe
@author_bp.route("/create_password", methods=["GET","POST"])
def create_password():
    form = PasswordForm()

    if form.validate_on_submit():
        new_author = Author(
            name = session.get('author_name'),
            email = session.get('author_email'),
            password_hash = Author.password(form.password.data)
        )
        db.session.add(new_author)
        db.session.commit()
        login_user(new_author)
        return redirect(url_for("user.dashboard"))

    return render_template("create_password.html", form = form)


#Rota para a página de login
@author_bp.route("/login", methods = ["GET",'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        author = Author.query.filter_by(email = form.email.data).first()
        
        if author and Author.check_password(author.password_hash, form.password.data):
            login_user(author)
            session['user'] = current_user.email
            return redirect(url_for("user.dashboard"))
        flash("Utilizador inexistente, tente novamente ou crie conta", "danger")
    return render_template("login.html", form = form)

#Rota de logout
@author_bp.route("/logout")
def logout():
    logout_user()
    flash("You where logged out")
    return redirect(url_for("user.login"))


#Rota do dashboard
@author_bp.route("/dashboard", methods=["GET","POST"])
@login_required
def dashboard():
    from extensions import UPLOAD_FOLDER
    
    form = PostForm()
    user_posts = Post.query.filter_by(author_id=current_user.id).all()

    filename = None  # Definir o filename antes de usá-lo

    if form.validate_on_submit():
        try:

            if form.image.data and not check_file(form.image.data.filename):
                flash("O ficheiro de imagem não é válido", "danger")
                return redirect(url_for("user.dashboard"))
            file = form.image.data
            if file:
                filename = secure_filename(file.filename)
                if not os.path.exists(UPLOAD_FOLDER):
                    os.makedirs(UPLOAD_FOLDER)
                file.save(os.path.join(UPLOAD_FOLDER, filename))
        
            new_post = Post(
                title=form.title.data,
                content=cleanify(form.content.data),
                author_id=current_user.id,
                photo=filename
            )
            db.session.add(new_post)
            db.session.commit()
            flash("Post created successfully", "success")  # Corrigido erro de digitação
            return redirect(url_for("user.dashboard"))
        except Exception as e:
            db.session.rollback()
            flash("Erro ao tentar iniciar sessão", "danger")

    return render_template("dashboard.html", form=form, posts=user_posts)


#Rota para deletar um post
@author_bp.route("delete_post/<int:id>", methods=['POST'])
def delete_post(id):
    post_to_delete = Post.query.get_or_404(id)
    try:
        db.session.delete(post_to_delete)
        db.session.commit()
        flash("Post deletected, successfully", "success")
        return redirect(url_for("user.dashboard"))
    except Exception:
        db.session.rollback()
        flash("Houve um erro ao eliminar o post", "warning")
        return redirect(url_for("user.dashboard"))

@author_bp.route("/edit_post/<int:id>", methods=["POST"])
def edit_post(id):
    return redirect(url_for("user.dashboard"))
  

#Rota para editar um post
@author_bp.route("/edit_user/<int:id>", methods=["POST"])
def edit_user(id):
    user_to_update = Author.query.get_or_404(id)
    try:
        if request.form:
            user_to_update.name = request.form.get('name')
            user_to_update.email = request.form.get('email')
            db.session.commit()
            return redirect(url_for("user.dashboard"))
    except Exception as e:
        flash("Não foi possível atualizar as informações", "danger")
        return redirect(url_for("user.dashboard"))
    

#Rota para ler os posts
@author_bp.route("/post_detail/<int:id>")
def post_detail(id):
    user_post_detail = Post.query.filter_by(id = id).first_or_404()
    return render_template("post_detail.html", post = user_post_detail)
    
 

routes/main_route.py
from flask import Blueprint, render_template
from models.post_model import Post

main_bp = Blueprint('index',__name__)



@main_bp.route("/")
def index():
    posts = Post.query.all()

    return render_template("index.html", posts = posts)

templates/create_password.html
{% extends 'index.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/create_password.css')}}"
/>
{% endblock %} {% block content %}
<main>
  <section class="imgage-content form-content">
    <div class="img">
      <img src="{{url_for("static", filename="images/password.svg")}}"
      alt="signup image" loading="lazy">
    </div>
  </section>

  <section class="form-content form-container">
    <form action="" method="post">
      <h3>Criar palavra-passe</h3>
      {{form.hidden_tag()}}
      <div class="data-input">
        {{form.password(class="form-control")}}
        {{form.password_confirm(class="form-control")}} {% if
        form.password.errors %}
        <ul>
          {% for error in form.password.errors %}
          <li class="error">{{error}}</li>
        </ul>
        {% endfor %} {% endif %} {{form.submit()}}
      </div>
    </form>
  </section>
</main>
{% endblock %}

templates/dashboard.html
{% extends 'index.html' %} {% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/dashboard.css')}}">
{% endblock %} {% block content %}
<main>

  <div class="alert">
    {% with messages = get_flashed_messages(with_categories = True) %}
      {% if messages %}
        {% for category, message in messages %}
      <div class="alert-content {{category}}">
        {{message}}
      </div>
      {% endfor %}
    {% endif %}
    {% endwith %}
  
  </div>

  <div class="dashboard">
    <div class="sub"><img class="sub-menu" src="{{url_for('static', filename='images/submenu.svg')}}" alt="sebmenu icon" loading="lazy"></div>
    <aside class="sidebar-menu">
      <nav class="dashboard-menu">
        <div class="sidebar-header">
          <span class="close">&times;</span>
        </div>
        <a href="#" class="sub-menu-icon" ><img class="sub-icon" src="{{url_for('static', filename='images/book.svg')}}" alt="post icon" loading="lazy">Posts</a>
        <button href="#" class="sub-menu-icon" id="write"><img class="sub-icon" src="{{url_for('static', filename='images/write.svg')}}" alt="edit icon" loading="lazy">Escrever</button>
      </nav>
    </aside>
    <!-- User side -->
      <section class="content">
        <div class="header-content">
          <div class="header-info">
            <div class="header-card">
              <div class="profile-pic">
                <img src="{{url_for('static', filename='images/user.svg')}}" alt="user icon" loading="lazy">
              </div>
              <div class="info">
                <h3 style="color: #2ecc71; font-weight: 500;">Informações do perfil</h3>
                <p>
                  Nome: <span>{{current_user.name}}</span>
                 </p>
                 <p>Email: <span>{{current_user.email}}</p></span>
              </div>
            </div>
            <div class="user-actions">

              <a href="{{url_for('user.logout')}}" class="sub-menu-icon"><img class="sub-icon" id="logout" src="{{url_for('static', filename='images/logout.svg')}}" alt="logout icon" loading="lazy">Sair</a>
              <button class="sub-menu-icon edit-user"><img class="sub-icon" id="logout" src="{{url_for('static', filename='images/write.svg')}}" alt="edit icon" loading="lazy">Editar</button>
              <a href="#" class="sub-menu-icon"><img class="sub-icon" id="logout" src="{{url_for('static', filename='images/delete.svg')}}" alt="delete icon" loading="lazy">Eliminar conta</a>
            </div>
          </div>  
          </div>
      </section>

      <!-- User edit section -->
      <section class="user-edit-form">
        <div class="edit-user-content">
          <span class="close-user-form" style="font-size: 26px; cursor: pointer;">&times;</span> <!-- Alterado aqui -->
          <h2>Atualizar dados</h2>
          <form action="{{url_for('user.edit_user', id=current_user.id)}}" method="post" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <input type="text" name="name" placeholder="Nome" class="user-edit" value="{{current_user.name}}">
            <input type="email" name="email" placeholder="Email" class="user-edit" value="{{current_user.email}}">
            <input type="submit" value="Atualizar">
          </form>
        </div>
      </section>


      <section class="posts">
        <h2>Artigos publicados</h2>

        <div class="post-content">
          {% if posts %}
            {% for post in posts %}
            <div class="post-card">
              <img src="" alt="">
              <h3 id="title{{post.id}}">{{post.title}}</h3>
              <p id="content{{post.id}}">
                {{post.content | safe | truncate(100, False, '...')}}
              </p>
              <span>Publicado em: {{post.published_date}}</span>
              <div class="actions">
                <button class="action btn-edit"
        id="{{ post.id }}"
        data-title="{{ post.title }}"
        data-content="{{ post.content|e }}"> 
        <img class="action-icon" src="{{ url_for('static', filename='images/edit2.svg') }}" alt="edit icon" loading="lazy">Editar
      </button>

      <button class="action btn_delete" id="{{post.id}}"> <img class="action-icon" src="{{url_for('static', filename='images/delete.svg')}}" alt="delete icon" loading="lazy">Eliminar</button>
              </div>
            </div>
            {% endfor %}
          {% else %}
            <p style="justify-content: center;">Sem posts publicados </p>
          {% endif %}
          
      </section>
    </div>
    <section class="new-post">
      <div class="new-post-content">
        <span class="close-post">&times;</span>
        <h2>Criar Novo Post</h2>
        <form action="" method="post" enctype="multipart/form-data">
           {{form.hidden_tag()}}
           {{form.title}}
           {{form.content|safe}}
           {{form.image}}
           {{form.submit}}
          </form>
      </div>
  </section>

  <section class="delete">
    <div class="delete_post">
      <form id="delete-form" method="post">
        {{form.hidden_tag()}}
        <p>Certeza que deseja eliminar o post?</p>
        <div class="delete-modal-buttons">
          <button type="submit" class="btn-confirm">Confirmar</button>
          <input type="reset" id="modal_delete" value="Cancelar">       
        </div>
      </form>
    </div>
  </section>

  <section class="edit">
    <div class="edit_post">
      <form action="" method="post" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        {{form.title}}
        <textarea name="edit_content" id="edit_content"></textarea>
        {{form.image}}
        {{form.submit}}
        {{ ckeditor.config(name='edit_content') }}
       </form>
    </div>
  </section>
  </div>
  {{ ckeditor.load() }} <!--Carrgar o ckEditor-->
  {{ ckeditor.config(name='content') }} <!--O elemento do formulário que receberá o-->
</main>
<script>
  let close_button = document.querySelector(".close");
  let dashboard_menu = document.querySelector(".sidebar-menu");
  let open_button = document.querySelector(".sub-menu");
  let main_content = document.querySelector(".content");

  let btn_delete = document.querySelectorAll(".btn_delete");
  let btn_edit = document.querySelectorAll(".btn-edit");
  let modal_delete = document.getElementById("modal_delete");
  let id;

  const btnEdit_user = document.querySelector(".edit-user");

  function closeSidebar() {
    if (window.innerWidth <= 768) {
      dashboard_menu.style.width = "0";
      main_content.style.marginLeft = '0';
      close_button.style.display = 'block';
    } else {
      dashboard_menu.style.width = "200px";
      main_content.style.marginLeft = '200px';
    }
  }

  function openSidebar() {
    dashboard_menu.style.display = "flex";
    dashboard_menu.style.width = "100%";
  }

  window.addEventListener("resize", closeSidebar);
  window.addEventListener("load", closeSidebar);

  close_button.addEventListener("click", closeSidebar);
  open_button.addEventListener("click", openSidebar);

  // Botão "Fechar" modal novo post
  document.querySelector(".close-post").addEventListener("click", () => {
    document.querySelector(".new-post").classList.remove("active");
  });

  // Botão "Fechar" modal de editar usuário
  document.querySelector(".close-user-form").addEventListener("click", () => {
    document.querySelector(".user-edit-form").classList.remove("active");
  });

  // Botão "Novo post"
  document.getElementById("write").addEventListener("click", () => {
    document.querySelector(".new-post").classList.add("active");
  });

  // Botão "Editar usuário"
  btnEdit_user.addEventListener("click", () => {
    document.querySelector(".user-edit-form").classList.add("active");
  });

  let delete_post = document.querySelector(".delete");

  // Modal delete
  btn_delete.forEach((btn) => {
    btn.addEventListener("click", function () {
      id = btn.getAttribute("id");
      delete_post.classList.add("active");
      document.getElementById("delete-form").action = `delete_post/${id}`;
    });
  });

  // Modal editar post
  btn_edit.forEach((btn) => {
    btn.addEventListener("click", function () {
      id = btn.getAttribute("id");
      const title = btn.dataset.title;
      const content = btn.dataset.content;
      document.querySelector(".edit").classList.add("active");

      setTimeout(() => {
        let ckeditorInstance = CKEDITOR.instances['edit_content'];
        if (ckeditorInstance) {
          ckeditorInstance.setData(content); // Preenche o editor com o conteúdo
        } else {
          console.warn("CKEditor não foi encontrado.");
        }
      }, 200);
    });
  });

  modal_delete.addEventListener("click", () => {
    console.log("Fechou modal");
    delete_post.classList.remove("active");
  });

  // Fechar o alerta depois de 3 segundos
  let alertInfo = document.querySelector(".alert-content");

  setInterval(() => {
    if (alertInfo && alertInfo.innerText) {
      document.querySelector(".alert").style.display = "none";
    }
  }, 3000);
</script>


{% endblock %}

templates/delete_post.html
<h1>Delete route</h1>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Finanças Jovem</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    <header>
      <nav class="nav-container">
        <h2 class="logo">
          <a href="{{url_for('index.index')}}">Finanças Jovem</a>
        </h2>
        <div class="hamburger" onclick="toggleMenu()">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </nav>
      <div class="mobile-menu" id="mobileMenu">
        <a href="">Sobre</a>
        {% if not current_user.is_authenticated %}
        <a href="{{url_for('user.login')}}">Iniciar sessão</a>
        <a href="{{url_for('user.register')}}" class="regist">Criar conta</a>
        {% else %}
        <a href="{{url_for('user.dashboard')}}" class="regist">Dashboard</a>
        {% endif %}
        <a href="#">Contacto</a>
      </div>
    </header>

    {% block content %}
    <section class="hero">
      <div class="hero-section">
        <h2>Comece a dominar seu dinheiro hoje!</h2>
      </div>
      <!-- <p>
        Dicas práticas, conteúdos simples e objetivos para te ajudar a dar os
        primeiros passos.
      </p> -->
    </section>

    <main class="main-content">
      <aside class="sidebar">
        <h3>Categorias</h3>
        <ul>
          <li><a href="#">Orçamento</a></li>
          <li><a href="#">Investimentos</a></li>
          <li><a href="#">Dicas Rápidas</a></li>
          <li><a href="#">Educação Financeira</a></li>
        </ul>
      </aside>

      <section class="posts">
        {% for post in posts %}
        <article class="post-card">
          <h4
            style="
              text-align: center;
              color: #2ecc71;
              font-size: 18px;
              font-weight: bold;
            "
          >
            {{post.title}}
          </h4>
          {% if post.photo %}
          <div>
            <img
              src="{{url_for('static', filename='images/' ~ post.photo)}}"
              alt="post image"
              width="200px"
              style="margin: auto"
              loading="lazy"
            />
          </div>
          {% endif %}
          <span
            >Publicado em: {{post.published_date.strftime("%d/%m/%Y")}}</span
          >
          <br />
          <br />
          <span>Por: <em>{{post.author.name}}</em></span>
          <p>{{post.content | safe |truncate(100, False, '...')}}</p>

          <a href="{{url_for('user.post_detail', id = post.id)}}">Ler mais</a>
        </article>
        {% endfor %}
      </section>
    </main>
    {% endblock %}

    <footer class="footer">
      <div class="container">
        <p>&copy; 2025 Finanças Jovem. Todos os direitos reservados.</p>
      </div>
    </footer>

    <script>
      function toggleMenu() {
        const menu = document.getElementById("mobileMenu");
        menu.classList.toggle("active");
      }
    </script>
  </body>
</html>

templates/login.html
{% extends 'index.html' %}

{% block head %}
  <style>
    main{
      display: flex;
      justify-content: center;
      flex-direction: column;
      align-items: center;
      background-color: #161b22;
   
    }
    a {
      text-decoration: none;
    }
    .form-container{
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      color: #fff;
      padding: 0 50px;
      margin-bottom: 30px;
      width: 100%;
    }
    form{
      width: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      border-radius: 10px;
    }
    .img img{
    width: 250px;
  }
  h3{
    text-align: center;
  }
  .data-input{
    border: 1px solid #ffffff68;
    padding: 30px;
    border-radius: 10px;
    width: 100%;
    max-width: 400px;
  }
  .form-control{
    margin: 10px 0;
  }
  .google{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin-bottom: 50px;
  }
  .google-link{
    display: flex;
    align-items: center;
    gap: 20px;

    border: 1px solid #ffffff68;
    padding: 20px;
    border-radius: 10px;
    text-decoration: none;
  }
  .google-logo{
    width: 35px;
  }
  .btn-primary{
    margin-top: 30px;
    width: 100%;
  }
  .login{
    margin: 10px;
  }
  </style>
{% endblock %}
 
{% block content %}
<main>
  <section class="imgage-content form-content">
    <div class="img">
      <img src="{{url_for("static", filename="images/login.svg")}}"
      alt="signup image">
    </div>
  </section>

  <section class="form-content form-container">
    <form action="" method="post">
      <h3>Iniciar sessão</h3>
      {% for message in get_flashed_messages() %}
        <p style="color: red;">{{message}}</p>
      {% endfor %}
      {{form.hidden_tag()}} 
      <div class="data-input">
        {{form.email(class="form-control w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500")}}
        {{form.password(class="form-control w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500")}}
        {{form.submit(class="btn btn-primary bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition")}}
      </div>
      <p style="margin-top: 7px; font-size: 12px; color: #4F46E5;"><a href="#">Esqueceu a palavra-passe ?</a></p>
      <p class="login">Não tem uma conta? <a href="{{url_for("user.register")}}" class="underline">Fazer cadastro</a></p>

    </form>
    <div class="google">
      <p>OU</p>
      <a href="{{url_for('user.OauthLogin')}}" class="google-link">
        <img src="{{url_for("static", filename="images/google.svg")}}"
        alt="GOOGLE LOGO" class="google-logo"> CONTINUE COM GOOGLE
      </a>
    </div>
  </section>
</main>
{% endblock %}

templates/post_detail.html
{% extends 'index.html' %} {% block head %}
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #161b22;
  }
  main {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
  }
  .container-content {
    padding: 50px;
    margin-top: 50px;
    color: #fff;
    background-color: #2ecc7081;
    text-align: center;
    width: 100%;
  }
  .container-content h1 {
    font-size: 50px;
    font-weight: bold;
  }
  .post-content {
    margin-top: 30px;
    padding: 20px;
    display: flex;
    justify-content: center;
    gap: 60px;

    width: 80vw;
  }
  .user-post {
    width: 100%;
  }
  .user-post h1 {
    margin-bottom: 10px;
    font-size: 26px;
  }
  .user-post p {
    margin-bottom: 5px;
  }
  .ads-section {
    margin-top: 40px;
    padding: 20px;
    background-color: #eee;
    border: 1px solid #ccc;
  }
  .ad {
    margin-bottom: 20px;
    padding: 15px;
    background-color: #fff;
    border: 1px solid #ddd;
    text-align: center;
  }
</style>
{% endblock %} {% block content %}
<main>
  <section class="container-content">
    <article>
      <h1 style="color: #fff">{{post.title}}</h1>
      <p>Por: {{post.author.name}}</p>
      <span>Publicado em:{{post.published_date.strftime("%d/%m/%Y")}}</span>
    </article>
  </section>

  <section class="post-content">
    <aside class="anunce-container"></aside>
    <article class="user-post">
      <p>{{post.content|safe}}</p>
    </article>
  </section>
</main>
{% endblock %}

templates/register.html
{% extends 'index.html' %}

{% block head %}
  <style>
    main{
      display: flex;
      justify-content: center;
      flex-direction: column;
      align-items: center;
      background-color: #161b22;
   
    }
    a {
      text-decoration: none;
    }
    .form-container{
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      color: #fff;
      padding: 0 50px;
      margin-bottom: 30px;
      width: 100%;
    }
    form{
      width: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      border-radius: 10px;
    }
    .img img{
    width: 250px;
  }
  h3{
    text-align: center;
  }
  .data-input{
    border: 1px solid #ffffff68;
    padding: 30px;
    border-radius: 10px;
    width: 100%;
    max-width: 400px;
  }
  .form-control{
    margin: 10px 0;
  }
  .google{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin-bottom: 50px;
  }
  .google-link{
    display: flex;
    align-items: center;
    gap: 20px;

    border: 1px solid #ffffff68;
    padding: 20px;
    border-radius: 10px;
    text-decoration: none;
  }
  .google-logo{
    width: 35px;
  }
  .btn-primary{
    margin-top: 30px;
    width: 100%;
  }
  .login{
    margin: 10px;
  }
  </style>
{% endblock %}
 
{% block content %}
<main>
  <section class="imgage-content form-content">
    <div class="img">
      <img src="{{url_for("static", filename="images/signup.svg")}}"
      alt="signup image">
    </div>
  </section>

  <section class="form-content form-container">
    <form action="" method="post">
      <h3>Criar conta</h3>
      {% for message in get_flashed_messages() %}
        <p style="color: red;">{{message}}</p>
      {% endfor %}
      {{form.hidden_tag()}} 
      <div class="data-input">
        {{form.name(class="form-control w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500")}}
        {{form.email(class="form-control w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500")}}
        {{form.submit(class="btn btn-primary bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition")}}
      </div>
    
      <p class="login">Já possui uma conta? <a href="{{url_for("user.login")}}" class="underline">Iniciar sessão</a></p>

    </form>
    <div class="google">
      <p>OU</p>
      <a href="{{url_for('user.OauthRegister')}}" class="google-link">
        <img src="{{url_for("static", filename="images/google.svg")}}"
        alt="GOOGLE LOGO" class="google-logo"> CONTINUE COM GOOGLE
      </a>
    </div>
  </section>
</main>

<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
crossorigin="anonymous"
></script>
{% endblock %}